name: Gerar XMLs

on:
  workflow_dispatch:

jobs:
  gerar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Gerar CT-e e MDF-e
        run: python engine/main.py

      - name: Commit contador
        run: |
          git config user.name "xml-bot"
          git config user.email "bot@github"
          git add state/contador.txt
          git commit -m "Incrementa contador"
          git push

      - name: Upload XMLs
        uses: actions/upload-artifact@v4
        with:
          name: xmls-gerados
          path: output/
